//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWinForm.ServiceReferenceSanPham {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SanPham", Namespace="http://schemas.datacontract.org/2004/07/ShopBanHang")]
    [System.SerializableAttribute()]
    public partial class SanPham : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HinhAnhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KichThuocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaDMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MauSacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoTaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoLuongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TrangThaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HinhAnh {
            get {
                return this.HinhAnhField;
            }
            set {
                if ((object.ReferenceEquals(this.HinhAnhField, value) != true)) {
                    this.HinhAnhField = value;
                    this.RaisePropertyChanged("HinhAnh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KichThuoc {
            get {
                return this.KichThuocField;
            }
            set {
                if ((object.ReferenceEquals(this.KichThuocField, value) != true)) {
                    this.KichThuocField = value;
                    this.RaisePropertyChanged("KichThuoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaDM {
            get {
                return this.MaDMField;
            }
            set {
                if ((object.ReferenceEquals(this.MaDMField, value) != true)) {
                    this.MaDMField = value;
                    this.RaisePropertyChanged("MaDM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((this.MaSPField.Equals(value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MauSac {
            get {
                return this.MauSacField;
            }
            set {
                if ((object.ReferenceEquals(this.MauSacField, value) != true)) {
                    this.MauSacField = value;
                    this.RaisePropertyChanged("MauSac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoTa {
            get {
                return this.MoTaField;
            }
            set {
                if ((object.ReferenceEquals(this.MoTaField, value) != true)) {
                    this.MoTaField = value;
                    this.RaisePropertyChanged("MoTa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((object.ReferenceEquals(this.SoLuongField, value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenSP {
            get {
                return this.TenSPField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSPField, value) != true)) {
                    this.TenSPField = value;
                    this.RaisePropertyChanged("TenSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TrangThai {
            get {
                return this.TrangThaiField;
            }
            set {
                if ((this.TrangThaiField.Equals(value) != true)) {
                    this.TrangThaiField = value;
                    this.RaisePropertyChanged("TrangThai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSanPham.IServiceSanPham")]
    public interface IServiceSanPham {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/All", ReplyAction="http://tempuri.org/IServiceSanPham/AllResponse")]
        ShopWinForm.ServiceReferenceSanPham.SanPham[] All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/All", ReplyAction="http://tempuri.org/IServiceSanPham/AllResponse")]
        System.Threading.Tasks.Task<ShopWinForm.ServiceReferenceSanPham.SanPham[]> AllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/ChiTietSP", ReplyAction="http://tempuri.org/IServiceSanPham/ChiTietSPResponse")]
        ShopWinForm.ServiceReferenceSanPham.SanPham ChiTietSP(int masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/ChiTietSP", ReplyAction="http://tempuri.org/IServiceSanPham/ChiTietSPResponse")]
        System.Threading.Tasks.Task<ShopWinForm.ServiceReferenceSanPham.SanPham> ChiTietSPAsync(int masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/SanPhamTheoLoai", ReplyAction="http://tempuri.org/IServiceSanPham/SanPhamTheoLoaiResponse")]
        ShopWinForm.ServiceReferenceSanPham.SanPham[] SanPhamTheoLoai(string loai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/SanPhamTheoLoai", ReplyAction="http://tempuri.org/IServiceSanPham/SanPhamTheoLoaiResponse")]
        System.Threading.Tasks.Task<ShopWinForm.ServiceReferenceSanPham.SanPham[]> SanPhamTheoLoaiAsync(string loai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/TimKiem", ReplyAction="http://tempuri.org/IServiceSanPham/TimKiemResponse")]
        ShopWinForm.ServiceReferenceSanPham.SanPham[] TimKiem(string loai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/TimKiem", ReplyAction="http://tempuri.org/IServiceSanPham/TimKiemResponse")]
        System.Threading.Tasks.Task<ShopWinForm.ServiceReferenceSanPham.SanPham[]> TimKiemAsync(string loai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/XoaSanPham", ReplyAction="http://tempuri.org/IServiceSanPham/XoaSanPhamResponse")]
        bool XoaSanPham(int masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/XoaSanPham", ReplyAction="http://tempuri.org/IServiceSanPham/XoaSanPhamResponse")]
        System.Threading.Tasks.Task<bool> XoaSanPhamAsync(int masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/SuaSanPham", ReplyAction="http://tempuri.org/IServiceSanPham/SuaSanPhamResponse")]
        bool SuaSanPham(int maspht, int masp, string tensp, string madm, decimal gia, string mota, string kichthuoc, string mausac, string hinhanh, string soluong, int trangthai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/SuaSanPham", ReplyAction="http://tempuri.org/IServiceSanPham/SuaSanPhamResponse")]
        System.Threading.Tasks.Task<bool> SuaSanPhamAsync(int maspht, int masp, string tensp, string madm, decimal gia, string mota, string kichthuoc, string mausac, string hinhanh, string soluong, int trangthai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/ThemSanPham", ReplyAction="http://tempuri.org/IServiceSanPham/ThemSanPhamResponse")]
        bool ThemSanPham(int masp, string tensp, string madm, decimal gia, string mota, string kichthuoc, string mausac, string hinhanh, string soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSanPham/ThemSanPham", ReplyAction="http://tempuri.org/IServiceSanPham/ThemSanPhamResponse")]
        System.Threading.Tasks.Task<bool> ThemSanPhamAsync(int masp, string tensp, string madm, decimal gia, string mota, string kichthuoc, string mausac, string hinhanh, string soluong);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSanPhamChannel : ShopWinForm.ServiceReferenceSanPham.IServiceSanPham, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSanPhamClient : System.ServiceModel.ClientBase<ShopWinForm.ServiceReferenceSanPham.IServiceSanPham>, ShopWinForm.ServiceReferenceSanPham.IServiceSanPham {
        
        public ServiceSanPhamClient() {
        }
        
        public ServiceSanPhamClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSanPhamClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSanPhamClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSanPhamClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ShopWinForm.ServiceReferenceSanPham.SanPham[] All() {
            return base.Channel.All();
        }
        
        public System.Threading.Tasks.Task<ShopWinForm.ServiceReferenceSanPham.SanPham[]> AllAsync() {
            return base.Channel.AllAsync();
        }
        
        public ShopWinForm.ServiceReferenceSanPham.SanPham ChiTietSP(int masp) {
            return base.Channel.ChiTietSP(masp);
        }
        
        public System.Threading.Tasks.Task<ShopWinForm.ServiceReferenceSanPham.SanPham> ChiTietSPAsync(int masp) {
            return base.Channel.ChiTietSPAsync(masp);
        }
        
        public ShopWinForm.ServiceReferenceSanPham.SanPham[] SanPhamTheoLoai(string loai) {
            return base.Channel.SanPhamTheoLoai(loai);
        }
        
        public System.Threading.Tasks.Task<ShopWinForm.ServiceReferenceSanPham.SanPham[]> SanPhamTheoLoaiAsync(string loai) {
            return base.Channel.SanPhamTheoLoaiAsync(loai);
        }
        
        public ShopWinForm.ServiceReferenceSanPham.SanPham[] TimKiem(string loai) {
            return base.Channel.TimKiem(loai);
        }
        
        public System.Threading.Tasks.Task<ShopWinForm.ServiceReferenceSanPham.SanPham[]> TimKiemAsync(string loai) {
            return base.Channel.TimKiemAsync(loai);
        }
        
        public bool XoaSanPham(int masp) {
            return base.Channel.XoaSanPham(masp);
        }
        
        public System.Threading.Tasks.Task<bool> XoaSanPhamAsync(int masp) {
            return base.Channel.XoaSanPhamAsync(masp);
        }
        
        public bool SuaSanPham(int maspht, int masp, string tensp, string madm, decimal gia, string mota, string kichthuoc, string mausac, string hinhanh, string soluong, int trangthai) {
            return base.Channel.SuaSanPham(maspht, masp, tensp, madm, gia, mota, kichthuoc, mausac, hinhanh, soluong, trangthai);
        }
        
        public System.Threading.Tasks.Task<bool> SuaSanPhamAsync(int maspht, int masp, string tensp, string madm, decimal gia, string mota, string kichthuoc, string mausac, string hinhanh, string soluong, int trangthai) {
            return base.Channel.SuaSanPhamAsync(maspht, masp, tensp, madm, gia, mota, kichthuoc, mausac, hinhanh, soluong, trangthai);
        }
        
        public bool ThemSanPham(int masp, string tensp, string madm, decimal gia, string mota, string kichthuoc, string mausac, string hinhanh, string soluong) {
            return base.Channel.ThemSanPham(masp, tensp, madm, gia, mota, kichthuoc, mausac, hinhanh, soluong);
        }
        
        public System.Threading.Tasks.Task<bool> ThemSanPhamAsync(int masp, string tensp, string madm, decimal gia, string mota, string kichthuoc, string mausac, string hinhanh, string soluong) {
            return base.Channel.ThemSanPhamAsync(masp, tensp, madm, gia, mota, kichthuoc, mausac, hinhanh, soluong);
        }
    }
}
