//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int MaDonHang { get; set; }
        public string IDUser { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<decimal> TriGiaDH { get; set; }
        public string MaTrangThai { get; set; }
    }
}
