//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string IDUser { get; set; }
        public string PassUser { get; set; }
        public string HoTenUser { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Ngaysinh { get; set; }
        public string Email { get; set; }
        public Nullable<int> Quyen { get; set; }
        public string ChucVu { get; set; }
        public Nullable<int> TrangThai { get; set; }
    }
}
